### ISSUE TITLE
Problems starting the file.

### ISSUE THREAD

**Issue by Masquerade64** [Datenlord1510/discord-predb#1]
I suffer this problem when attempting to run the file with python. Is there something I am doing incorrectly?

`main.py

Traceback (most recent call last):
  File "D:\Downloads\discord-predb-main\main.py", line 4, in <module>
    from PYxREL import xREL
  File "D:\Downloads\discord-predb-main\PYxREL\__init__.py", line 1, in <module>
    from .xREL import xREL
  File "D:\Downloads\discord-predb-main\PYxREL\xREL.py", line 1, in <module>
    from .APIHelper import APIHelper
  File "D:\Downloads\discord-predb-main\PYxREL\APIHelper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

**Comment by Datenlord1510** [comment]
Thanks for opening up the issue.
I made a mistake by thinking that the requests module is part of the standard library, but it is in fact an external module.
I added a requirements.txt and edited the README.

You can install the requests module by using either of these two approaches:

`pip install requests`
`pip install -r requirements.txt`


For Python3 use pip3 instead.

**Comment by mefflecakes** [comment]
I'm not sure what's going on, but i had the issue that was raised, but even after trying both of the commands mentioned above, it still says:

    import requests
ModuleNotFoundError: No module named 'requests'

I verified that the module was installed (which it was) and i could uninstall it to try each method.

**Comment by Datenlord1510** [comment]
That's a common hiccup when your Python setup struggles to find the installed modules. I don't know what your setup is, but you could try running it with "python main.py" instead of "python3 main.py". [This answer on StackOverflow](https://stackoverflow.com/questions/17309288/importerror-no-module-named-requests) also provides good guidance.
Another option is to use virtual enviroments for Python, you can find the [documentation here](https://docs.python.org/3/library/venv.html) and a good answer in [post on StackOverflow](https://stackoverflow.com/questions/35017160/how-to-use-virtualenv-with-python). They explain it better than I could.

Also, if you are using Python3, you should use pip3.

**Comment by mefflecakes** [comment]
Got further but both my windows installation an dlinux both now say the following:

Request failed: Expecting value: line 1 column 1 (char 0)


I only have python3 & pip3 installed on each of these. Not sure if that helps.

**Comment by Datenlord1510** [comment]
That certainly is a step further! It seems like the json response from the API is not correct, which I haven't encountered before. Can you try to print the "response.text" in PYxREL -> APIHelper.py? I'd put it directly under line 13, which is 'response = requests.get(api_url, params=parameters)'. I also made a new commit and changed the error handling a bit, which hopefully gives more information.

**Comment by mefflecakes** [comment]
Sorry, I don't code or script - so I'm not exactly sure what you'd like me to do with \discord-predb-main\PYxREL\APIHelper.py

Apologies if this is frustrating, hopefully other users will find this useful though.

**Comment by Datenlord1510** [comment]
No problem! I made a new commit that will print the response.text for you in the error message. Just grab the new code, or only the new PYxREL folder, from the repo and let me know what the new error message is.

**Comment by mefflecakes** [comment]
Cool, thanks!

I now see this:

Invalid response format: Expecting value: line 1 column 1 (char 0)
Response content: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"><meta http-equiv="refresh" content="35"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: "api.xrel.to",cType: 'non-interactive',cNounce: '99579',cRay: '81683008abd954e1',cHash: '03c6d8cd719eaaf',cUPMDTk: "\/v2\/release\/browse_category.json?category_name=WINDOWS&per_page=25&page=1&__cf_chl_tk=dgZi7MSSQXLpU0kseMpV2mESVFrN5gIa1mcvVnfwKFc-1697374224-0-gaNycGzNCiU",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '60000',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/v2\/release\/browse_category.json?category_name=WINDOWS&per_page=25&page=1&__cf_chl_f_tk=dgZi7MSSQXLpU0kseMpV2mESVFrN5gIa1mcvVnfwKFc-1697374224-0-gaNycGzNCiU",md: "Mf1yxFYT8JT26BoxmQbvJAqWZwh3pQgnJxGTlA1gSfM-1697374224-0-AZZzHjj7QVmMjkwAnnWOJdx6UZ4AMn7jwirnjaLO6Ls5hNb4BnCxA0wxPPO1UfpPtExA5WhffLD-J_aRwWRmRR8loaQpkDFPw0HIKH4mbT6SpSUjP7V1eEuhiA4OvEVou7I2_81yQsJXwsVfP7aTEGiMrix_nrwP_f4FwefHMlD1bEo2OVoMDiFj8Zqd3CXySuCXZhbIMJ4oA7IDq23z2dE6qXncuQ1nYfZ6pbhpWKVqwYM7sIUcXo1uDjWgM8ACiBFTksfGRGL6t1ODW4CTZOqVg8oYg7J2kkU83AF940kQmpAo9Ou6Dg9rZ_zdGQLhTOFriklAAe-TcCDMOdBXfO4QEHlVnpfGQK9INvJ0ktAzI8xKqFCY5vrRiX-2fiWnzIf0TR27CpsHF-BkCFJsTnSs93wyAtezYjKuaM_vuDkfs3TuhcPOO0yxfjDbFBOHbwJFivYbBv_3hUDHFVM-s1PHXI0wasfXqlv2nM7F8q-1N36_CDnV2AaPi66OXQVI2j414u6ehKvhf0C74U3QL5h-kQLZ5mEnq0A45GW0dmoGM7UleTVed_LW4c0HbdIgFuOe2kv3f70Ck0xWNcr6Xsv_UZDci8kdOwMzpb1qnRfbDPKq4nW7LKRsfda_QuYzb0aCnhwDLuQ6cMcIfbj8guIJhPd_O5k8cUaHSUhb-IWlfWPkkZK8GQQSVb-8ALlh6F-oYFROqWmYO6OQDZA25RrpuAuxPcbwTewc6bDbYsdkianDIUj3opF0n8ICUOX89-X2TKaaDr2WtYCXeR_DtlvQgXVDBDp_5gcxNL2odjfa448I94Kl1Dno6c9IybvNpAoi1gtvL7p6DicOjDy2Y156SvCC7NNSPTfwJXGWClpSMEpT5ddUoFWersnoJZNYiXD1C4f4qg69J8nri7CZGlGHlbP0-jsSkw0cFT00KYD6AhLkCT_JM8fEtz0WQg96EyAhx1i5nCNdUvpWFsnXaeE_Ciq-aVJEiaBMz5VhDavPbYxOfoKlh9u6vQJU_edhspBhj-j5Zr9CYn3V3Sirt2qkmkUHS_YGnvVtalC4clS2ezys5_O-yJIa6vNE8FJdwXqqrC-KiqXkOjay_DYrjAsrDZYMFPqc6MVMrLCGkE39VWXoEzSwgNoIrCISMxLe-_V7XHEHy04aOq71Js5A-r2DR6xW93geKF7MvMzqc42KqCJRGXS2FFRbPfgMrQimrR8y-33z0V6kUTqzWgasyAKI8BmK1IoA9KDW3LAgrO-vF-xScPauSqpbgxqzt8homdCmb7CBt1mTvmSxO9oGDPADVsHpzMpZri2Gg8SoziAFGffJ8_7Y_L-UffOBHZdwMrPmicuzsYxMkTER4fmCN3AJr2N24S-iG-zuSPnBBj-1AlDTKvSiKrf6w44ZqgXrB2mwtfyl8iakroa3rjM5ySVGzE1-IlTZU9tPLpk2zirbaJKMRgCz80LB3EHlN7XkJA3dWBiKKvCo31crNwSb081obTODFWmoipmO-kcoyTuWXxhWkMgcYI7ppEAKTdMFADDS6gZkOp6mgxjQEz99-3UTEwW1nnLrNzNTZd2d5mF1MLfE7qy6ghBJ9EtbIfPPI7rJMsBwlU-0YoUJY_TGXb_wibGii-SwVf8crAs3Kdgp7wuwnif-xiQdxUtotn8N26wOfssdAD1nmx_Q3BLBMQ8xz_-adZ_xvP6kC_xbz6ppRcYIqczuzNhsVi5rx_8L9XdK3tEjtTEG0tikhPLr19QuTg0Z-yRnAozG77XNQSkVhaZ_4jkd82LyUjiKvsXrCkzBcD0JZQWQxQVO-ULY2QOLYQd4JB7h6ol3XcCtcO_6NuD3LVa4XfmO_Rcs8luI5CjkFG1WgI27vvJ_JTSOY8LRD58omf-g0ZQQZ9zDML8XtD6M-GHTadUoZGhcJTRhWYyUqktl3JWOr3d8JNmI22_Zu6NMZwhpmc7SbxFBJX4YU8hch7tuMhXzBBf_ip5nMW73g4n_i3sAAS9_9wSK1XndI5fs3SGsNUOLn77tQxzcKsXBfau5IwauSVl6IXOL_OHGSPbgWCRa6zFTk3GDKU1mHuxlXGjnZwyxz5fglTl4u4V6JqVIyzauB39MGiT9fJgEn2wrAt8EaDBV1ZQxYw9tzzuPxGcHp2ue1veqQ6B3gwIE7HWVDQPhaekl4SLvQolJXrxci3D7GiCUPgf65u0diZ3sTi81MnXstXNm4lxka0CwLRT_-eqqzQVLpFWY9Xi1pi3-XIPop1Z7D7wEKF7hJ2ozIer4qFM5EGsa86PpXikg8skVblLhh12FA6KyX0NqJRXsu4PIsWZUHkVENPzDLkuYjDcc8Hl8RWz8JUcNXw8YJL2Q8_fqddOP6VLCgUKCBDb954Q4SgbiO_cmp2_3_nCXnkvLjBsZo0OJPl0Qn84vOGXneY7Ugt5h8WY67m3-qqy0i0uz4UpOtJpbfX2uho-9VQ2VN5FXyXmA2CnCfEEtQJ33GsgFCNiYXO21P7l-tD7SAquiTNfwNeNCDh_e4HqUxrXir8PWKOzsK25C",cRq: {ru: 'aHR0cHM6Ly9hcGkueHJlbC50by92Mi9yZWxlYXNlL2Jyb3dzZV9jYXRlZ29yeS5qc29uP2NhdGVnb3J5X25hbWU9V0lORE9XUyZwZXJfcGFnZT0yNSZwYWdlPTE=',ra: 'cHl0aG9uLXJlcXVlc3RzLzIuMzEuMA==',rm: 'R0VU',d: 'pa503mPW2R2QRzho6nmZkyHqd0VYfxUxcjjEMlMucHuMjz5vaszd4FFutJNmKCK/0+pBoGAbTqLRkqxdGL1tTT/4xAdKUYvPDaOxQvGs2K2IoPdmtJSOR4wD1AL7d5RNcUJ/fndHGgnNuY5Nkbzv6VuSQgnfpbuIQJIJxlyW1r1flyktC4hawzv5hemgSsZ5ArF9ZB7NqIkB8eAeWs33XN0Ylr4iViEQ8pUq+7ufGYOBmniemgN9ro18MkUGGqFoXLBz6NopTsNVmXSvLGb3iPmFZPzPUyzDanix4OFR553ojeWnV50VCTbqjDE2fujm5Hh0N+TS4/S1HZ9QzKtPFIznwl973wfD4gJEuXcrNiL9Xe7rg7bv+FfighWU+xFzvj2zGOa5eRj4Jlp2LP6k3TSGveO9d39Cd0MaHa3sWLJEBtR3fd/pNBrqIbSFp3uTYN49ZS7u9OXEDlHbHj96X54HPaPNFiRHibDP2yGaudI=',t: 'MTY5NzM3NDIyNC43NDIwMDA=',cT: Math.floor(Date.now() / 1000),m: 'scm1dK0VhoKpBA3Ut/uavHeDi3Yc8l7G0sr2AoMgFms=',i1: '/VvabiIpUYf40QbPcYzMHQ==',i2: 'KVRGkzmkYHIMabxpdZZgPQ==',zh: 'VS/oI6zvIBkRQFLeBbOsIaoFLSE8w8F5zsmk73T9OX4=',uh: 'YE9XOpG5TeHmhA1zfs5mxC8CrRZzq2a/+r+OU7dliYQ=',hh: 's07/+mnx/6mgldqItHQewUtiukCAdnvVYOvnr/003Ik=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=81683008abd954e1';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/v2\/release\/browse_category.json?category_name=WINDOWS&per_page=25&page=1&__cf_chl_rt_tk=dgZi7MSSQXLpU0kseMpV2mESVFrN5gIa1mcvVnfwKFc-1697374224-0-gaNycGzNCiU" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>

**Comment by Datenlord1510** [comment]
How weird! It seems xREL has implemented additional security measures using Javascript. That might be due to rate limiting or IP blocking. 
Have .json files been created in the directory where main.py is located? If they are there, are they filled with content?

**Comment by mefflecakes** [comment]
nope, no .jason file in there. by the way, is it possible to customize feeds easily, for things like movies, or would that require af fundamental code change?

**Comment by mefflecakes** [comment]
i don't get the error when disabling my VPN,i suppose it must be that. i don't see anything appear in discord yet, although it might need a new release to report first?

**Comment by Datenlord1510** [comment]
Yeah, it must be the VPN! They state in their documentation "Important info: due to abusive requests to xrel.to, we had to block some IP ranges including some VPN providers. If this is a problem for you, please use https://xrel-api.nfos.to/ to access the API instead of https://api.xrel.to/.".  Glad it works now though!

Yes, the first time there won't be a message, because it does an intial scan, so it does need a new release. But you can run test.py and should get a message to your webhooks immediately to cofirm everything works.
